arrowParens: 'avoid'
singleQuote: true
bracketSpacing: true
endOfLine: 'lf'
semi: false
tabWidth: 2
trailingComma: 'none'
proseWrap: always
plugins:
  - prettier-plugin-astro
  - prettier-plugin-tailwindcss
pluginSearchDirs: false
