services:
  gov:
    image: ghcr.io/lex-unix/babyn-yar-gov:latest
    restart: unless-stopped
    ports:
      - 8080:4321
    depends_on:
      api:
        condition: service_healthy
  admin:
    image: ghcr.io/lex-unix/babyn-yar-admin:latest
    restart: unless-stopped
    ports:
      - 8082:80
    depends_on:
      api:
        condition: service_healthy
  api:
    image: ghcr.io/lex-unix/babyn-yar-api:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/v1/healthcheck']
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.0.11-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
  migrate:
    image: migrate/migrate:v4.16.2
    profiles:
      - 'tools'
    volumes:
      - ./migrations:/migrations
    entrypoint:
      - 'migrate'
      - '-path'
      - '/migrations'
      - '-database'
      - '${DATABASE_URL}'
    command:
      - 'up'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
volumes:
  db-data:
  redis:
