version: '3'

# TODO add depends_on to clients
services:
  gov:
    build:
      context: .
      dockerfile: ./apps/gov/Dockerfile
    restart: always
    ports:
      - 8081:80
  org:
    build:
      context: .
      dockerfile: ./apps/org/Dockerfile
    restart: always
    ports:
      - 8080:80
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:alpine
    restart: always
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
