name: Cleanup old images

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.PAT }}
          image-names: 'babynar-yar-*'
          cut-off: 1d
          keep-at-least: 3
          untagged-only: true
          dry-run: true
