name: publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  ACTOR: ${{ github.actor }}

jobs:
  publish:
    name: publish ${{ matrix.app }} image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app: gov
            dockerfile: ./apps/gov/Dockerfile
            image: babyn-yar-gov

          - app: admin
            dockerfile: ./apps/admin/Dockerfile
            image: babyn-yar-admin

          - app: api
            dockerfile: ./Dockerfile
            image: babyn-yar-api

    steps:
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ACTOR }}
          password: ${{ secrets.PAT }}

      - name: build and push ${{ matrix.app }} image
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.dockerfile }}
          build-args: |
            API_URL=${{ secrets.API_URL }}
            PUBLIC_API_URL=${{ secrets.PUBLIC_API_URL }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ matrix.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

